version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "%(asctime)s - %(threadName)s - %(name)s - %(levelname)s - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: ./logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: ./logs/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

root:
    level: DEBUG
    handlers: [console, info_file_handler, debug_file_handler]
    propogate: yes

loggers:
    healthchecks:
        propogate: yes
    
    notifications:
        propogate: yes

    statuspage_io:
        propogate: yes